
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-17T19:17:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1100aec5374248b932db9e7e11e0e5463587a131",
 "version": "4.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
